version: "3.8"

services:
  db:
    image: postgres:13
    container_name: quiz-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: quizdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: quiz-app
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
      - "5555:5555"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/quizdb

volumes:
  pgdata:
